const gameData = {
    // Arrays de nombres divididos por género
    nombres: {
        masculino: [
            "Juan",
            "Pedro",
            "Luis",
            "Carlos",
            "Diego",
            "Fernando",
            "Javier",
            "Miguel",
            "Andrés",
            "Alberto",
            "Eduardo",
            "Santiago",
            "Arturo",
            "Ricardo",
            "Felipe",
            "Raúl",
            "Pablo",
            "Victor",
            "Gabriel",
            "Emilio",
        ],
        femenino: [
            "María",
            "Laura",
            "Ana",
            "Sofía",
            "Carla",
            "Lucía",
            "Elena",
            "Isabel",
            "Valeria",
            "Gabriela",
            "Claudia",
            "Natalia",
            "Sara",
            "Patricia",
            "Carmen",
            "Ana María",
            "Silvia",
            "Teresa",
            "Mónica",
            "Diana",
        ],
    },

    // Arrays de textos predefinidos para las peticiones
    textosPeticion: {
        "crear cuenta": [
            "El cliente {nombre} ha solicitado crear una nueva cuenta.",
            "{nombre} desea abrir una cuenta bancaria para sus ahorros.",
            "Una solicitud de creación de cuenta ha sido presentada por {nombre}.",
            "El cliente {nombre} quiere comenzar a usar los servicios del banco abriendo una cuenta.",
            "{nombre} ha visitado el banco para crear una nueva cuenta.",
        ],
        "cerrar cuenta": [
            "{nombre} ha solicitado cerrar su cuenta bancaria.",
            "El cliente {nombre} ya no necesita su cuenta y ha pedido cerrarla.",
            "{nombre} quiere finalizar todos sus vínculos con el banco y ha solicitado el cierre de su cuenta.",
            "El cliente {nombre} desea proceder con la cancelación de su cuenta bancaria.",
            "Una petición de cierre de cuenta ha sido recibida por {nombre}.",
        ],
        "extraer efectivo": [
            "{nombre} quiere extraer ${cliente.value} de su cuenta bancaria.",
            "El cliente {nombre} ha solicitado retirar ${cliente.value} en efectivo.",
            "{nombre} desea realizar una extracción de ${cliente.value}.",
            "Una solicitud de extracción de ${cliente.value} ha sido presentada por {nombre}.",
            "El cliente {nombre} quiere retirar ${cliente.value} de su cuenta hoy.",
        ],
        "ingresar efectivo": [
            "{nombre} ha solicitado ingresar ${cliente.value} a su cuenta bancaria.",
            "El cliente {nombre} quiere depositar ${cliente.value} en su cuenta.",
            "Una solicitud para ingresar ${cliente.value} en efectivo ha sido presentada por {nombre}.",
            "{nombre} desea depositar ${cliente.value} en su cuenta bancaria.",
            "El cliente {nombre} está aquí para ingresar ${cliente.value} en su cuenta.",
        ],
        "transferir dinero": [
            "{nombre} ha solicitado transferir ${cliente.value} a la cuenta de ${cliente.dni_dest}.",
            "El cliente {nombre} quiere realizar una transferencia de ${cliente.value} a ${cliente.dni_dest}.",
            "Una transferencia de ${cliente.value} ha sido solicitada por {nombre} hacia ${cliente.dni_dest}.",
            "{nombre} desea enviar ${cliente.value} a la cuenta de ${cliente.dni_dest}.",
            "El cliente {nombre} quiere transferir ${cliente.value} a ${cliente.dni_dest}.",
        ],
        "activar tarjeta": [
            "{nombre} ha solicitado activar una tarjeta bancaria.",
            "El cliente {nombre} quiere activar su nueva tarjeta.",
            "Una solicitud de activación de tarjeta ha sido presentada por {nombre}.",
            "{nombre} desea activar su tarjeta bancaria para poder usarla.",
            "El cliente {nombre} quiere proceder con la activación de su tarjeta.",
        ],
        "desactivar tarjeta": [
            "{nombre} ha solicitado desactivar su tarjeta.",
            "El cliente {nombre} quiere proceder con la desactivación de su tarjeta bancaria.",
            "{nombre} desea desactivar su tarjeta para evitar cualquier uso.",
            "Una petición de desactivación de tarjeta ha sido recibida de parte de {nombre}.",
            "El cliente {nombre} quiere que se desactive su tarjeta lo antes posible.",
        ],
    },
};

// Exportar el objeto para que pueda ser usado en otros archivos
export { gameData };
